//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class arizaliurunasamasi
    {
        public int arizaliurunasamasi_ { get; set; }
        public Nullable<int> arizaliurun_ { get; set; }
        public Nullable<int> personel_ { get; set; }
        public Nullable<int> asamasayisi { get; set; }
        public string aciklama { get; set; }
        public Nullable<bool> gordu { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
    
        public virtual arizaliurun arizaliurun { get; set; }
        public virtual personel personel { get; set; }
    }
}
