//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class arizaliurunfotograf
    {
        public int arizaliurunfotograf_ { get; set; }
        public string url { get; set; }
        public Nullable<int> arizaliurun_ { get; set; }
    
        public virtual arizaliurun arizaliurun { get; set; }
    }
}
