//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class teknikservisdbEntities : DbContext
    {
        public teknikservisdbEntities()
            : base("name=teknikservisdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<arizaliurunfotograf> arizaliurunfotograf { get; set; }
        public virtual DbSet<arizamusterisi> arizamusterisi { get; set; }
        public virtual DbSet<personeltip> personeltip { get; set; }
        public virtual DbSet<urunfirsat> urunfirsat { get; set; }
        public virtual DbSet<urunkatagori> urunkatagori { get; set; }
        public virtual DbSet<urunmarka> urunmarka { get; set; }
        public virtual DbSet<urunsepeti> urunsepeti { get; set; }
        public virtual DbSet<urunsiparis> urunsiparis { get; set; }
        public virtual DbSet<adres> adres { get; set; }
        public virtual DbSet<il> il { get; set; }
        public virtual DbSet<ilce> ilce { get; set; }
        public virtual DbSet<firma> firma { get; set; }
        public virtual DbSet<personel> personel { get; set; }
        public virtual DbSet<urunmodel> urunmodel { get; set; }
        public virtual DbSet<arizaliurun> arizaliurun { get; set; }
        public virtual DbSet<urunmusteri> urunmusteri { get; set; }
        public virtual DbSet<arizaliurunasamasi> arizaliurunasamasi { get; set; }
    }
}
