//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class urunfirsat
    {
        public int urunfirsat_ { get; set; }
        public Nullable<int> urunsiparis_ { get; set; }
        public Nullable<int> personel_ { get; set; }
        public Nullable<int> asamasayisi { get; set; }
        public Nullable<System.DateTime> firsattarihi { get; set; }
        public string aciklama { get; set; }
    
        public virtual urunsiparis urunsiparis { get; set; }
        public virtual personel personel { get; set; }
    }
}
