//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class urunsiparis
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public urunsiparis()
        {
            this.urunfirsat = new HashSet<urunfirsat>();
            this.urunsepeti = new HashSet<urunsepeti>();
        }
    
        public int urunsiparis_ { get; set; }
        public Nullable<int> urunmusteri_ { get; set; }
        public Nullable<System.DateTime> siparistarih { get; set; }
        public Nullable<double> toplamucret { get; set; }
        public Nullable<int> siparisdurumu { get; set; }
        public Nullable<int> personel_ { get; set; }
        public Nullable<int> odemetip { get; set; }
        public Nullable<double> satisfiyat { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<urunfirsat> urunfirsat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<urunsepeti> urunsepeti { get; set; }
        public virtual personel personel { get; set; }
        public virtual urunmusteri urunmusteri { get; set; }
    }
}
