//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class urunsepeti
    {
        public int urunsepeti_ { get; set; }
        public Nullable<int> urunmodel_ { get; set; }
        public Nullable<int> urunsiparis_ { get; set; }
        public Nullable<int> urunsayisi { get; set; }
        public Nullable<double> toplamucret { get; set; }
    
        public virtual urunsiparis urunsiparis { get; set; }
        public virtual urunmodel urunmodel { get; set; }
    }
}
